.catalog:
  name: Gitlab Community
  version: 8.8.2-0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.sarrc.ru"
      type: "string"
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of Gitlab storage dir"
      required: true
      default: "/data/gitlab"
      type: "string"
    - variable: "HOSTLABEL"
      description: "Run on host with this label "
      label: "Host label:"
      required: true
      default: "hostname=site"
      type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true

