.catalog:
  name: transcard Site
  version: 1.0
  description: |
    transcard Site
  minimum_rancher_version: v0.56.0
  uuid: transcard-0
  questions:
    - variable: "main_path"
      description: "Path to conf.d and etc."
      label: "Path to conf.d and etc."
      required: true
      default: "/rancher/transcard"
      type: "string"
    - variable: "HOSTLABEL"
      description: "Run on host with this label "
      label: "Host label:"
      required: true
      default: "hostname=galaxydata"
      type: "string"

nginx:
  scale: 1
php:
  scale: 1
www-data:
  scale: 1

