.catalog:
  name: "Registry"
  version: "v3.1"
  description: "Docker Registry"
  uuid: registry-0
  questions:
    - variable: "DBPASSWORD"
      label: "DB Password"
      description: "Password for Portus database access, must be 8 characters or longer"
      required: true
      default: password
      type: "password"
    - variable: "ROOTPASSWORD"
      label: "DB Root Password"
      description: "Root Password for MySQL database, must be 8 characters or longer.  This is not normally used."
      required: true
      default: password
      type: "password"
    - variable: "DIR"
      label: "Storage directory"
      description: "Path of shared storage to use for registry, database, and certificates.  This should be available on all hosts"
      required: true
      default: "/rancher/registry"
      type: "string"
    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server.  This should be the CN in the certificates and will be the URL to contact the Registry and Web interface"
      required: true
      default: "registry.sarrc.ru"
      type: "string"
    - variable: "HOSTLABEL"
      description: "Run on host with this label "
      label: "Host label:"
      required: true
      default: "hostname=rancher"
      type: "string"
db:
  scale: 1
registry:
  scale: 1
portus:
  scale: 1
